const clubData = [
    {
      clubName: "Tech Innovators Club",
      createdBy: ObjectId("609a1f9d1f292efc5d97bcf7"),
      aboutUs: "A club for students passionate about technology and innovation.",
      logo: "https://example.com/logos/tech_innovators.png",
      foundedYear: 2018,
      president: "John Doe",
      vicePresident: "Jane Smith",
      email: "contact@techinnovators.com",
      phoneNumber: "123-456-7890",
      socialMedia: {
        facebook: "https://facebook.com/techinnovators",
        twitter: "https://twitter.com/techinnovators",
        instagram: "https://instagram.com/techinnovators",
      },
      membershipFee: 50,
      totalMembers: 120,
      achievements: ["Won 1st prize in Hackathon 2020", "Organized TechFest 2021"],
    },
    {
      clubName: "Art & Culture Club",
      createdBy: ObjectId("609a1f9d1f292efc5d97bcf8"),
      aboutUs: "Promotes art and culture through events, exhibitions, and workshops.",
      logo: "https://example.com/logos/art_culture.png",
      foundedYear: 2015,
      president: "Alice Green",
      vicePresident: "Bob White",
      email: "info@artcultureclub.com",
      phoneNumber: "987-654-3210",
      socialMedia: {
        facebook: "https://facebook.com/artcultureclub",
        instagram: "https://instagram.com/artcultureclub",
      },
      membershipFee: 30,
      totalMembers: 90,
      achievements: ["Hosted Art Week 2022", "Community outreach programs"],
    },
    {
      clubName: "Literature Society",
      createdBy: ObjectId("609a1f9d1f292efc5d97bcf9"),
      aboutUs: "For those passionate about literature, writing, and poetry.",
      logo: "https://example.com/logos/literature_society.png",
      foundedYear: 2020,
      president: "Samuel Harris",
      email: "literature@society.com",
      phoneNumber: "111-222-3333",
      socialMedia: {
        twitter: "https://twitter.com/literaturesociety",
      },
      membershipFee: 20,
      totalMembers: 45,
      achievements: ["Published annual magazine", "Organized poetry reading sessions"],
    },
    {
      clubName: "Environmental Club",
      createdBy: ObjectId("609a1f9d1f292efc5d97bcfa"),
      aboutUs: "Focuses on environmental awareness and sustainability.",
      logo: "https://example.com/logos/environmental_club.png",
      foundedYear: 2017,
      president: "George Brown",
      vicePresident: "Lisa Ray",
      email: "eco@club.com",
      phoneNumber: "555-123-4567",
      socialMedia: {
        facebook: "https://facebook.com/environmentalclub",
        instagram: "https://instagram.com/environmentalclub",
      },
      membershipFee: 15,
      totalMembers: 100,
      achievements: ["Planted 1000 trees", "Conducted waste management workshops"],
    },
    {
      clubName: "Music & Dance Club",
      createdBy: ObjectId("609a1f9d1f292efc5d97bcfb"),
      aboutUs: "A platform for students to showcase musical and dance talents.",
      logo: "https://example.com/logos/music_dance_club.png",
      foundedYear: 2016,
      president: "Nina Patel",
      email: "music@danceclub.com",
      phoneNumber: "333-444-5555",
      socialMedia: {
        facebook: "https://facebook.com/musicdanceclub",
        twitter: "https://twitter.com/musicdanceclub",
      },
      membershipFee: 25,
      totalMembers: 80,
      achievements: ["Annual dance competition winner", "Hosted music nights"],
    }
  ];
  
  module.exports = clubData;
  